### ISSUE TITLE
Docker.runconfig's mmlspark package coordinates out of date

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#399]
Using SDK version `1.0.10`: the default `Docker.runconfig` uses out of date Maven coordinates for `mmlspark`

It gives:
```yaml
  spark:
# List of spark repositories.
    repositories:
    - https://mmlspark.azureedge.net/maven
    packages:
    - group: com.microsoft.ml.spark
      artifact: mmlspark_2.11
      version: '0.12'
    precachePackages: true
```
but it should be:
```yaml
  spark:
# List of spark repositories.
    repositories:
    - https://mmlspark.azureedge.net/maven
    packages:
    - group: Azure
      artifact: mmlspark
      version: '0.17'
    precachePackages: true
```
@hning86 is this even necessary if I'm using a Docker baseImage like, `microsoft/mmlspark:gpu`?
cc: @jpe316 @akshay-0
