### ISSUE TITLE
[Notebook issue] Error when trying to request prediction from the model being served on the web service (Pytorch)

### ISSUE THREAD

**Issue by Ali-Parandeh** [Azure/MachineLearningNotebooks#538]
**Describe the bug**
When sending a request to the model on the web service, I receive the error below.

```python
AvgPool2d' object has no attribute 'divisor_override'
``` 

Provide the following if applicable:
+ Your Python & SDK version 
SDK version: 1.0.53, Python 3.6 - AzureML

+ Python Scripts or the full notebook name
Sample -1.0.55 - train-hyperparameter-tune-deploy-with-pytorch.ipynb
+ Pipeline definition 
```python
   compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_NC6', 
                                                           max_nodes=4)
```
+ Environment definition 
```yml
name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
  - azureml-defaults==1.0.53.*
  - torch
  - torchvision
channels:
- conda-forge
```

+ Example data 
+ Any log files. 

```python
WebserviceException: Received bad response from service:
Response Code: 502
Headers: {'Connection': 'keep-alive', 'Content-Length': '54', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Tue, 20 Aug 2019 11:24:27 GMT', 'Server': 'nginx/1.10.3 (Ubuntu)', 'X-Ms-Request-Id': '37c29a42-336e-4585-8337-56135097f203', 'X-Ms-Run-Function-Failed': 'True'}
Content: b"'AvgPool2d' object has no attribute 'divisor_override'"
```

+ Run and Workspace Id 
```
Workspace name: azure-pytorch
Azure region: uksouth
Resource group: pytorch
```

**To Reproduce**
1.  Just run through the notebook
2. Run code below after model is deployed on web service

```python
input_data = preprocess('test_img.jpg')
result = service.run(input_data=json.dumps({'data': input_data.tolist()}))
print(result)
```

**Expected behavior**
Printing result
**Additional context**
