### ISSUE TITLE
Pip configuration

### ISSUE THREAD

**Issue by wagenrace** [Azure/MachineLearningNotebooks#643]
What if you have custom internal python package in azure and want to use them in the estimator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c6df68-5739-e8db-1acb-38f5a504ce7c
* Version Independent ID: b9664417-0785-378c-c082-5e63bd1b3f6a
* Content: [azureml.train.estimator.Estimator class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-core/azureml.train.estimator.estimator?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-core/azureml.train.estimator.Estimator.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by swanderz** [comment]
our team has a custom python package published to Azure Artifacts that our `conda_dependencies` points to... here's our example:

## `conda_dependencies.yml`
```YAML
name: project_environment
dependencies:
  - python=3.6.2
  - pip:
      - pip
      - azureml-defaults==1.0.72
      - azureml-pipeline==1.0.72
      - azureml-core==1.0.72
      - azureml-dataprep
      - interpret-community==0.1.0.2
      - numpy
      - pandas==0.25.1
      - imbalanced-learn
      - shap==0.30.1
      - pytest
      - pytest-json-report
      - lifelines
      - lightgbm
      - scikit-learn
      - pygit2
      - joblib
      - artifacts-keyring --pre
      - --extra-index-url https://pypi.python.org/simple
      - --index-url https://pypackages3:xcju6y3cqhtybq4lcawwnnkzt3hq3uu7kfo76g5466kaciefqp6q@avanade-its.pkgs.visualstudio.com/_packaging/pypackages3/pypi/simple/
      - mlpackage==0.0.7
      - azure-cosmos
```
